name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with: 
        version: latest
    - name: Run Buildx
      run: |
        docker login -u ${{secrets.hub_name}} -p ${{secrets.hub_pass}}
        docker buildx build \
            -t mq83/myss1 \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            . \
            --push

